/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mahoa;

import javax.swing.JFrame;

/**
 *
 * @author MY ASUS
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CBBthuattoan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Các Thuật Toán Mã Hóa");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jLabel2.setText("Lựa Chọn Phương Thức Mã Hóa");
        getContentPane().add(jLabel2, java.awt.BorderLayout.LINE_START);

        CBBthuattoan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Caesar", "HoanVi", "Affine", "Vigenere", "Hill", "RSA" }));
        CBBthuattoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBBthuattoanActionPerformed(evt);
            }
        });
        getContentPane().add(CBBthuattoan, java.awt.BorderLayout.CENTER);

        jButton1.setText("Mở Thuật Toán");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String thuattoan = CBBthuattoan.getSelectedItem().toString();
        switch (thuattoan){
            case "Caesar":{
                JFrame jf = new JFrame();
                CaesarScreen cs = new CaesarScreen();
                jf.add(cs);
                jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jf.setSize(500, 400);
                jf.setVisible(true);
            };
            break;
            case "HoanVi":{
                JFrame jf = new JFrame();
                HoanViScreen hvs = new HoanViScreen();
                jf.add(hvs);
                jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jf.setSize(500, 400);
                jf.setVisible(true);
            };
            break;
            case "Affine":{
                JFrame jf = new JFrame();
                AffineScreen as = new AffineScreen();
                jf.add(as);
                jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jf.setSize(500, 400);
                jf.setVisible(true);
            };
            break;
            case "Vigenere":{
                JFrame jf = new JFrame();
                VigenereScreen vs = new VigenereScreen();
                jf.add(vs);
                jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jf.setSize(500, 400);
                jf.setVisible(true);
            };
            break;
            case "Hill":{
                JFrame jf = new JFrame();
                HillScreen hs = new HillScreen();
                jf.add(hs);
                jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jf.setSize(500, 400);
                jf.setVisible(true);
                
            };
            break;
             case "RSA":{
                JFrame jf = new JFrame();
                RSAPanel rsa = new RSAPanel();
                jf.add(rsa);
                jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                jf.setSize(500, 400);
                jf.setVisible(true);
            };
            break;
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CBBthuattoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBthuattoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBBthuattoanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBBthuattoan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
